# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (
        lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import users_types_pb2 as users__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='users.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b('\n\x0busers.proto\x1a\x11users_types.proto2\x85\x01\n\x05Users\x12?\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x17.users.CreateUserResult\x12;\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x15.users.GetUsersResult0\x01\x62\x06proto3'),
    dependencies=[
        users__types__pb2.DESCRIPTOR,
    ])


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_USERS = _descriptor.ServiceDescriptor(
    name='Users',
    full_name='Users',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=35,
    serialized_end=168,
    methods=[
        _descriptor.MethodDescriptor(
            name='CreateUser',
            full_name='Users.CreateUser',
            index=0,
            containing_service=None,
            input_type=users__types__pb2._CREATEUSERREQUEST,
            output_type=users__types__pb2._CREATEUSERRESULT,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name='GetUsers',
            full_name='Users.GetUsers',
            index=1,
            containing_service=None,
            input_type=users__types__pb2._GETUSERSREQUEST,
            output_type=users__types__pb2._GETUSERSRESULT,
            options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_USERS)

DESCRIPTOR.services_by_name['Users'] = _USERS

# @@protoc_insertion_point(module_scope)
